### ISSUE TITLE
HIPAA technical details page: build out ref arch details 

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-io.github.io#468]
https://github.com/gruntwork-io/gruntwork-io.github.io/pull/456#discussion_r673977607

**Comment by zackproser** [comment]
This issue was originally discrete, but given our latest conversations, and design evolutions, this is now a duplicate of #490

**Comment by brikis98** [comment]
Which conversations are those? Shoving both items into the same page seems to create a page that's large and hard to navigate / understand...
