### ISSUE TITLE
HIPAA landing page: Step 5 screenshot changes

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-io.github.io#470]
In Step 5, “Stay up to date automatically via Terraform pull requests,” the current screenshot is a bit hard to read. Perhaps instead, we show a screenshot of versioned releases from the terraform-aws-eks repo?. Or a screenshot from a RenovateBot PR showing the diff page with an upgrade from version X to Y?

**Comment by ebeneliason** [comment]
@zackproser I'm not entirely clear on what screen you're suggesting we show. Is it this one? https://github.com/gruntwork-io/terraform-aws-eks/tags. I'm not sure if I have access to RenovateBot.

**Comment by brikis98** [comment]
This was originally my request. 

This page was what I had in mind: https://github.com/gruntwork-io/terraform-aws-eks/releases. However, using a little web developer tools magic to strip out unnecessary stuff so more versions are visible. Example:

![Screen Shot 2021-07-23 at 11 25 46 AM](https://user-images.githubusercontent.com/711908/126769619-0cf20be6-86ac-4f25-a5fc-635a6e177c97.png)

As for the RenovateBot idea, I was thinking of the PRs opened by it. Here's an example: https://github.com/gruntwork-io/terraform-aws-service-catalog/pull/827. Example diff:

![Screen Shot 2021-07-23 at 11 26 55 AM](https://user-images.githubusercontent.com/711908/126769735-6ddaeea8-9783-4206-a909-d465a828d895.png)

**Comment by ebeneliason** [comment]
Thanks. At small scale, I think the diff reads more clearly at a glance. Let's roll with that!
