### ISSUE TITLE
HIPAA bootstrap your app: left align check boxes

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-io.github.io#475]
NIT: left align the check-boxes, as in the home page footer.

Currently it seems we have identical markup and styling applied to this section as in the home page and pricing page where it's working correctly, but perhaps because of the way we're loading it through a template the final markup is not structured properly to have the content centered while the check mark icons are all left-aligned.

**Comment by ebeneliason** [comment]
There was an inline style missing. Corrected with https://github.com/gruntwork-io/gruntwork-io.github.io/pull/494
