### ISSUE TITLE
I'm interested button on pricing page goes awry on mobile

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/gruntwork-io.github.io#491]
<img width="531" alt="Screen Shot 2021-07-22 at 2 04 54 PM" src="https://user-images.githubusercontent.com/296757/126709398-5a08371d-b390-40c4-962d-38330a50904d.png">

**Comment by ebeneliason** [comment]
@pete0emerson I'm not seeing this issue. Is this still a problem for you? What browser? 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/687448/126717850-ce8bb24a-6a57-462b-841d-6229e3305daa.png">

**Comment by pete0emerson** [comment]
This appears to be fixed.
