### ISSUE TITLE
HIPAA technical details page: code viewer nits

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-io.github.io#504]
As @ebeneliason reported:
    1. The blue border around the tabs isn't showing up for some reason. But, I see the CSS for it…
   2.  The gray background on the code block that's shorter than the code box should ideally extend to fill the box. Maybe the background color is on the wrong element.

**Comment by ebeneliason** [comment]
@zackproser Is there anything left to do here, or should we close this issue?

**Comment by zackproser** [comment]
This is now resolved! Closing it out.
