### ISSUE TITLE
HIPAA page may want to mention testing / enforcement / self-auditing

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#526]
Per some feedback from customers, something our HIPAA landing page should mention is how we test for compliance, enforce it on an ongoing basis, and "prove" compliance through self-auditing code. In particular, we may want to call out:

1. Terratest to test basic functionality.
2. Some off-the-shelf compliance-checking solution we use to give you a green check or red "X."
3. OPA policies to enforce compliance on an on-going basis. This seems especially popular these days.

**Comment by zackproser** [comment]
Updating this with our latest thinking: 

-  Gruntwork's HIPAA Reference Architecture is configured out-of-the-box to work with compliance scanning tools, so you have continuous monitoring and alerts on your compliance status. Image: Screenshot of AWS Security Hub with green check marks next to a list of requirments 
- Gruntwork's HIPAA Architecture comes with a CI/CD pipeline that runs your code against a library of OPA policies to validate that every commit remains in compliance with HIPAA requirements. Image: An OPA code snippet, perhaps taken from [the OPA homepage](https://www.openpolicyagent.org/)
