### ISSUE TITLE
Should we detail how to configure Patcher in the landing Page?

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#534]
Think through a bit more if we need to detail _how_ you configure Patcher in our landing pages (either a web UI or a `patcher.yml` config). Might be too much detail at this stage though.

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by ina-stoyanova** [comment]
I believe we're answering exactly this already in this PR: https://github.com/gruntwork-io/gruntwork-io.github.io/pull/584 
@marinalimeira @brikis98 thoughts?

**Comment by brikis98** [comment]
Yea, prob the new images in #584 and the new How it Works page in #557 will be enough.

**Comment by brikis98** [comment]
Closing in favor of the two items mentioned above.
