### ISSUE TITLE
Add a comparison table to Patcher landing page

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#535]
Add a comparison table. The columns should be competitors and then Patcher: 
- Do nothing,
- DependaBot, 
- RenvoateBot, 
- Snyk, 
- Patcher.

Rows will be things like: 
- works with all version control systems (DependaBot is GitHub only), 
- supports version number bumps (yes for all of them), 
- can patch breaking changing (yes only for Patcher), 
- auto discovers dependencies (yes for all of them), 
- can manually identify dependencies (yes only for RenovateBot and Patcher), 
- can build dependency graph (yes only for Patcher? @robmorgan has more thoughts on this), 
- security patching (yes for all), 
- internal dependency management (yes only for Patcher?).

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by robmorgan** [comment]
PR: https://github.com/gruntwork-io/gruntwork-io.github.io/pull/558
