### ISSUE TITLE
Which VCS integrations should we support first with the launch?

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#536]
Consider if we should support 1-2 other VCS integrations beyond GitHub out of the gate to better support enterprises. Perhaps GitHub Enterprise is easy to support if you already have a GitHub App? Probably most popular VCS for enterprises is BitBucket. So perhaps **GitHub + BitBucket** are the launch VCS tools?
- Ask customers if necessary

**Comment by marinalimeira** [comment]
The contact form has the option to choose a VCS.

**Comment by ina-stoyanova** [comment]
Good idea, this way we can gather interest levels for each option. @brikis98 @robmorgan what do you both think?

**Comment by brikis98** [comment]
Oh, that's a clever idea @marinalimeira. OK, let's update the language across the Patcher landing page to specify all common VCS (GitHub, BitBucket, GitLab), and use the contact form to see which ones customers actually want.

**Comment by ina-stoyanova** [comment]
(chatitng with @marinalimeira live:)
- The contact page now supports that: https://github.com/gruntwork-io/gruntwork-io.github.io/pull/549 (Still needs to be merged in)
- On the landing page, we still need to call out the support we're offering.

**Comment by ina-stoyanova** [comment]
Mentioned on the comparison page Github, Bitbucket, and Gitlab
