### ISSUE TITLE
List future support for more VCS tools

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#537]
List that support for other VCS tools (GitLab, etc) is coming in the future.
- Maybe ask customers, or the community support users

**Comment by ina-stoyanova** [comment]
Also moving to v2. @robmorgan what we discussed.

**Comment by ina-stoyanova** [comment]
fast fingers! Closed by mistake!

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by ina-stoyanova** [comment]
Ok, picking this one up. We've currently listed on the comparison page we support Github, Gitlab and Bitbucket. Do we want to offer anything else? Potentially CodeCommit is a good option, but I suspect that Mercurial, TFS and others are not as crucial.

**Comment by brikis98** [comment]
Ah, I think somewhere along the way, we changed our plans to say we support GitHub, GitLab, and BitBucket, and have users tell us which they want in the contact form. I don't think we need to add CodeCommit or anything else at this stage. We should update all pages to indicate exactly this though. E.g., I just left some comments in https://github.com/gruntwork-io/gruntwork-io.github.io/pull/584 to that effect.

**Comment by ina-stoyanova** [comment]
Yep, we indeed made that call! That's good news. I'll close this issue then.
