### ISSUE TITLE
Should we replace the Grunty cubes on the Patcher landing page?

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#539]
The Grunty cubes to the left of the hero section of the Patcher landing page don't add much value. Perhaps replace with a `.gif` showing the Patcher workflow (maintainer releases new version with patch, end user gets a PR with updates)? Or tabs with a few screenshots?

**Comment by ina-stoyanova** [comment]
I wonder if we could reuse indeed some of the gifs that @marinalimeira is creating. 

_Thinking out loud:_ 
If we stick a screenshot of a mocked up UI, then we are almost committing that this is what it's going to look like, without having spent enough time or resources on the design itself. Maybe that's ok?

**Comment by brikis98** [comment]
> I wonder if we could reuse indeed some of the gifs that @marinalimeira is creating.

Perhaps!

> _Thinking out loud:_
> If we stick a screenshot of a mocked up UI, then we are almost committing that this is what it's going to look like, without having spent enough time or resources on the design itself. Maybe that's ok?

I think that's true of everything on the landing pages. It's the nature of putting something out there that isn't really done.

It also occurs to me that the top of the page currently doesn't make it clear that the product the user is looking at is called Patcher!

![Screen Shot 2021-08-16 at 7 04 13 PM](https://user-images.githubusercontent.com/711908/129706660-2f77c849-d751-4bcb-a72b-62f274f3351d.png)

The only mention of Patcher is in the subtext, which is easy to miss! So, I think to fix this bug we should:

1. Replace "Gruntwork Labs" on this landing page with "Patcher."
2. Replace the Grunty image with something more meaningful. A Patcher logo? An image that represents keeping things up to date? A `.gif` showing the rough experience?

**Comment by ina-stoyanova** [comment]
>The only mention of Patcher is in the subtext, which is easy to miss! So, I think to fix this bug we should:

Wow, you're right!! How did we miss it! I'll replace the text to be "Patcher" and see if we can do some logo.... indeed, or reuse the gifs from Marina!

**Comment by ina-stoyanova** [comment]
Ok, here's the 2 options @marinalimeira and I came out with:
<img width="415" alt="Screenshot 2021-08-17 at 17 53 08" src="https://user-images.githubusercontent.com/32835571/129749119-4e60323a-64a6-4f1b-a48d-89dde40bdd24.png">
<img width="387" alt="Screenshot 2021-08-17 at 17 54 16" src="https://user-images.githubusercontent.com/32835571/129749338-c0202788-18f5-4a4d-b477-8bc0f85fe00b.png">

**Comment by brikis98** [comment]
@ina-stoyanova Assigning to you as I believe this is what you fixed in #597.
