### ISSUE TITLE
 Replace logos below hero text on Patcher landing page

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#540]
Right now, the landing page has AWS, K8S, and Terraform logos, which don't make much sense for a Patcher landing page. Replace these with something else. Perhaps the "supported tech" logos, at much smaller size each, should go in this section?

**Comment by ina-stoyanova** [comment]
This is actually done. https://github.com/gruntwork-io/gruntwork-io.github.io/pull/552/commits/7104fc6b52735d7c719660ab2b7853c03f2305e2
