### ISSUE TITLE
Create separate "How it Works" page for Patcher

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#541]
Go into a bit more detail of how maintainers create Patches and how Patcher executes those. [See show, don't tell here](https://www.notion.so/gruntwork/Patcher-backwards-incompatible-internal-dependency-workflows-2e260347cd6a470384c998e22a0c1895#1b890fd631044390b896f5509e242b92).

One thing to consider for this page is two views: an "end user" view and a "maintainer" view. Each view (tab?) shows the experience for that party. E.g., The End user installs a GitHub app, gets PRs with updates, reviews the code, sees tests run, and merges. The maintainer updates their code, creates a patch, tests the patch with a `patcher` CLI, and then creates a new release in GitHub.

**Update**: I flushed this idea out more [below](https://github.com/gruntwork-io/gruntwork-io.github.io/issues/541#issuecomment-896131059).

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by brikis98** [comment]
Some thoughts on the design of this page:

1. It could have two top level tabs at the top: one labeled "Library Maintainer Workflow" and one labeled "Library User Workflow." See this [HIPAA page](https://www.gruntwork.io/hipaa-compliance-on-aws/technical-details) for an example of this layout.
2. Within each tab, we can use the "zig zag" layout as usual to tell each story.
3. The maintainer zig zag could be something like:
    1. Update the code for your library. Make changes to your library the usual way: create a branch, make some changes, and open a pull request.
    1. Run tests against all users of your library. Patcher discovers all users of your library within your company, runs their automated tests with your updated code, and gives you a report if those tests passed. That way, you know how your changes affect your downstream users before merging!
    1. Create a patch file. If you are making backwards incompatible changes, you can create a Patch file to automatically upgrade the code of your library's users. Patch files can perform text transformations (e.g., add a new input variable) as well as execute custom scripts (e.g., run some CLI tools).
    1. Run tests against your patch. You can use `patcher plan` and `patcher apply` to test your patch against a repo. Patcher will also run your patch against all users of your library in a temporary branch and run their tests, so you can see check if both your code changes and patch are working.
    1. Merge and release. Merge and release as usual: e.g., create a new Git tag for the new version of your library, or push your new versioned artifact (e.g., `.jar`) to Artifactory.
4. The user zig zag could be something like:
    1. Install Patcher. It's a GitHub App.
    1. Patcher auto discovers your dependencies. It does this automatically. You can also help it along with manual hints.
    1. Patcher patches your code and opens a PR. When a maintain releases new code, Patcher automatically opens a PR to update you to the new version. If the new version included a patch, Patcher executes the Patch too, and the updated code is part of the PR.
    1. You review and merge. You see the code changes and test results in the Patch and can safely merge when you're happy.

**Comment by robmorgan** [comment]
I'm working on implementing these latest changes in https://github.com/gruntwork-io/gruntwork-io.github.io/pull/557. Besides a few code blocks, I'm wondering if I should also use animated GIFs to explains some of these items.

**Comment by brikis98** [comment]
Animated `.gif` could def help!

**Comment by robmorgan** [comment]
I've updated the text blocks in #557, but left the images as HIPAA images. I'll have to think about the GIF ideas tomorrow. Ideas welcome!
