### ISSUE TITLE
Replace Grunty on cubes for the zig zag on the Patcher page

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#542]
Put in screenshots or `.gif` or more useful images to show what Patcher does.

**Comment by brikis98** [comment]
Thanks Marina!

Yes, I think screenshots or `.gif` images similar to Patcher would be right. E.g.,

1. "Install the Patcher GitHub App" could be a screenshot of the GitHub UI when you go to install a GitHub App.
1. "Patcher discovers your dependencies automatically" is an interesting one... Some ideas:
    1. A list of commonly supported formats: `package.json`, `build.gradle`, `Gemfile`, `source` URLs in `.tf` and `.hcl` files, `Go.mod`, `Go.sum`, etc. 
    1. A mock up of some Patcher web UI that shows the list of dependencies we found in a given repo. 
    1. The text from running the `patcher` CLI: e.g., some sort of `patcher list-dependencies` command that shows the list of dependencies found in a repo. 
    1. An example of how to manually help Patcher find a version via a special comment (similar to [these](https://github.com/gruntwork-io/terraform-aws-service-catalog/blob/master/modules/base/ec2-baseline/install.sh#L7-L12), but of course focused on Patcher, not RenovateBot).
    1. Looking at the list above, perhaps we do a few tabs: a "Supported dependency formats" tab with the list of supported formats (e.g., `package.json`), a "Inspecting dependencies" tab could show the `patcher list-dependencies` CLI output, and a "Manually define dependencies" tab could show a code snippet with a special comment.
1. "Maintainers release new versions and patches" could have a couple tabs: one tab shows the releases page of some GitHub repo (e.g., our EKS repo) to show you release new versions "as usual," and the other tab shows an example Patch file.
1. Etc.

These are just starting ideas, so feel free to get creative.

**Comment by marinalimeira** [comment]
@brikis98 what is a `patcher file`? Its like a ruby script?

**Comment by brikis98** [comment]
It's the file format we'll create to define patches (e.g., a patch to update from TF 0.14 -> 0.15). I don't know what the format will be yet; we'l have to design it. E.g., Could be a YAML file that declares transformations to run and/or scripts to execute; could be something else.
