### ISSUE TITLE
Make the list of supported tools / languages look nicer on Patcher landing page

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#543]
The big white logos aren't particularly nice looking. See "supported languages" on [this page](https://web.archive.org/web/20190323092226/https://dependabot.com/) for a possible alternative design.

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by ina-stoyanova** [comment]
@brikis98 also wondering what you think here, and how it looks now?

<img width="1005" alt="Screenshot 2021-08-17 at 12 26 43" src="https://user-images.githubusercontent.com/32835571/129700550-9152536c-238b-47eb-8f5d-4ced1f1b59bc.png">

**Comment by brikis98** [comment]
What's there now looks great! I think this can be closed.
