### ISSUE TITLE
Create use cases page for Patcher

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#546]
This should have real-world examples of where Patcher is useful ([see here for context](https://www.notion.so/gruntwork/Patcher-backwards-incompatible-internal-dependency-workflows-2e260347cd6a470384c998e22a0c1895#e1d912f93f9d4932b1cda9cd2d2a874b)). We could tell the Gruntwork story as one use case (i.e., maintain IaC Lib for hundreds of companies); we should definitely tell the internal maintainer story (e.g., `util.jar`, `security.jar`); we can tell the Terraform 0.12 upgrade story (painful backwards incompatible upgrade); we should tell a security focused story (talk about some vulnerability where you needed to do a backwards incompat change quickly to fix a huge security hole).

**Comment by ina-stoyanova** [comment]
Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by ina-stoyanova** [comment]
We'll do this separately, as it needs more thinking than we had time. Moving it to patcher-v2

**Comment by brikis98** [comment]
I suspect this one will need to be done ASAP; otherwise, the landing page may be missing the "viable" in "minimal viable product." Without seeing concrete examples of what Patcher lets them do, I'm not sure many will have enough imagination to guess themselves, and sign up.

**Comment by infraredgirl** [comment]
Proposed text for use case 1. PTAL and suggest improvements, then I can incorporate them and write the rest of the use cases.

### Use case 1: Update to Terraform 0.12 automatically

You can use Patcher to automatically update a codebase containing Terraform modules to a new Terraform version, including new major verions that contain backwards incompatible changes. Patcher will scan your codebase and open a pull request, such as the one shown in the screenshot below, that transforms your code to use the new version of Terraform. For example, Terraform 0.12 had a particularly painful backwards incompatible upgrade (details?), but Patcher can make such upgrades as painless and smooth as reviewing and merging a PR.

<img width="1803" alt="tf12" src="https://user-images.githubusercontent.com/1786860/128891381-7419a05d-07b8-4280-9f84-d73cb91c3055.png">

**Comment by infraredgirl** [comment]
Thanks for the input @brikis98! Next steps for me to work on:

- [ ] Incorporate Jim's comments into the text
- [ ] Create a "use cases" page: use the zig-zag structure; fill out the first use case
- [ ] Fill out the rest of the use cases
