### ISSUE TITLE
Improve design of features section for Patcher

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#547]
It's not too readable right now

**Comment by ina-stoyanova** [comment]
> Check out the [DependaBot page in the web archive](https://web.archive.org/web/20190323092226/https://dependabot.com/) for inspiration on how they tell their story.

**Comment by ina-stoyanova** [comment]
Hey @brikis98 I wonder what's your take on how it looks right now? 

<img width="1079" alt="Screenshot 2021-08-17 at 12 25 31" src="https://user-images.githubusercontent.com/32835571/129700363-9523bb36-40cb-442c-aad2-b77e078f7132.png">

**Comment by brikis98** [comment]
I think it's an improvement, but a few ideas for ways to make it even better:

1. Something about the colors in the icons makes it seem like they are in deep, dark shadows. I'm not sure why, but I find it slightly offputting. Would using white instead of black for edges/shadows look better? Alternatively, we could have _just_ the icons without the cubes: e.g., solely the checkbox, lightning bolt, plus sign, etc, without the cube underneath each one.
1. Since we have a comparison table now, no need to say "Like DependaBot" or "Unlike DependaBot."

**Comment by ina-stoyanova** [comment]
1. Ok, thanks for the feedback. We want a different reaction, so I'll make some time to play around with different icons. 
2. Very true. Will update the text too.

**Comment by ina-stoyanova** [comment]
Picking this one up again.
