### ISSUE TITLE
Why an image above the Patcher zig zag?

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#567]
I'm curious why we have a new image above the "zig zag" portion of the Patcher landing page?

![Screen Shot 2021-08-09 at 7 50 09 PM](https://user-images.githubusercontent.com/711908/128758410-3c2d1d03-9237-45b0-8215-3c25c3473851.png)

The icons in the image are nice, and it is a concise way to show what Patcher does, but I have a few concerns:

1. It seems to repeat the content of the zig zag below, so it feels a bit redundant.
2. The text below the icons is _really_ small and hard to read.
3. It doesn't call out the key differentiator of supporting breaking changes.

Perhaps the icons could be used in the zig zag itself? Or was the idea to use this instead of a zig zag?

**Comment by ina-stoyanova** [comment]
I believe this is actually the first attempt of the how it works section, when it wasn't animated, or a separate page. I think @robmorgan and I made the call to add this image, and then swap it for the real plan of how it works, but in the meantime it ended up duplicating the content of the zig-zag section below. 

I believe we've now got these 2 PRs on the case, which means we should/could remove this image:
- https://github.com/gruntwork-io/gruntwork-io.github.io/pull/557
- https://github.com/gruntwork-io/gruntwork-io.github.io/pull/584

**Comment by brikis98** [comment]
Ah, gotcha. An animation on the landing page (to replace Grunty, as per #539) would be great if we could get it working. Otherwise, it's probably clearer to drop the image for now.

**Comment by ina-stoyanova** [comment]
Noted. I'm not sure if @robmorgan had planned something at some point, but I can remove it for now from the landing page.
