### ISSUE TITLE
Landing pages bug: horizontal scrollbar on pricing table

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/gruntwork-io.github.io#573]
In all the landing pages, there is a horizontal scrollbar on the pricing table:

<img width="1095" alt="Screen Shot 2021-08-09 at 2 48 07 PM" src="https://user-images.githubusercontent.com/430092/128765343-6f8a7310-754a-4cb1-b328-765659d2b30f.png">

**Comment by ina-stoyanova** [comment]
I'm not sure I can see this happening, has it been dealt with in the mentioned PR? Also looked for comments there, but couldn't find the reference.

**Comment by brikis98** [comment]
I'll take a look at this one
