### ISSUE TITLE
Less blurry images for EKS landing page

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#593]
A few of the images on the EKS landing page are blurry:

1. Infrastructure Code
2. README.md
3. TFC
4. Stay up to date

For each one, we should do one of the following:

1. Replace with a less blurry image, if such an image is possible in such a tight space
2. Replace with a crisp `.gif`
3. Replace with a code snippet

**Comment by yorinasub17** [comment]
We're using JIRA (at least for Enterprise EKS). We should move the others as well, according to https://gruntwork-io.slack.com/archives/C0275GS2FKM/p1628539270275000

If there is doubt about that, we should discuss.

This ticket is covered by https://gruntwork.atlassian.net/browse/WWW-124 where I have questions waiting for feedback.

**Comment by brikis98** [comment]
Doh! Completely forgot about the JIRA ticket. My bad.
