### ISSUE TITLE
Make it clear that the Enterprise EKS subscription replaces the subscription for existing Gruntwork customers

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#595]
[Feedback from a customer](https://twitter.com/haplomephistos/status/1427605127964266496):

> The site looks great! Having some information about how the licensing/pricing works for existing customers with subscriptions would be helpful. It isn't entirely clear if it is a new subscription, or would/could be included if you have existing subscriptions.

We should update the pricing page to make it clearer that the Enterprise EKS subscription is an upgrade for most existing customers that would replace their existing Gruntwork subscription. Perhaps add to FAQ?

**Comment by yorinasub17** [comment]
Moved to JIRA (https://gruntwork.atlassian.net/browse/WWW-128) as per our discussion in thread https://gruntwork-io.slack.com/archives/C0275GS2FKM/p1628539270275000

We should try to move the other issues over too.
