### ISSUE TITLE
Alignment issue for eks tabs on landing page

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#606]
There's an issue with some of the tabs on the EKS landing page. That causes the whole page to be wider than is expected and is scrollable.
<img width="383" alt="Screenshot 2021-08-19 at 17 01 38" src="https://user-images.githubusercontent.com/32835571/130082560-805458af-84da-45e7-bd79-aa8a21f92715.png">

<img width="399" alt="Screenshot 2021-08-19 at 17 01 30" src="https://user-images.githubusercontent.com/32835571/130082554-bc9ae444-83cc-4a35-8cbb-a4c9f24595c1.png">

**Comment by marinalimeira** [comment]
<img width="438" alt="Screen Shot 2021-08-19 at 16 07 49" src="https://user-images.githubusercontent.com/9384479/130083214-28451e70-16c3-4b55-aa83-477145a9cc49.png">

The alignment with the text its a bit weird also
