### ISSUE TITLE
Wide images in Patcher landing page break the flow a bit

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/gruntwork-io.github.io#616]
The [Patcher home page](https://www.gruntwork.io/patcher) zig-zag now includes a few wide images: e.g., "Use the UI" and "You review and merge." I believe this was done so the images aren't shrunk by the browser and are more legible, and it's a lovely creative solution. However, the drawback to this is that it breaks the flow, making it hard to follow the page. The text now goes left-center-left-right-center, and what's a headline and what's not is thrown off. Users typically don't read a page, but skim headlines quickly (we've confirmed this from user testing too), so it's important the headlines are laid out in a consistent way that's easy to skim.

I can think of two options:

1. Go back to the original image sizes / zig-zag flow. Resize the images [as described here](https://gruntwork.atlassian.net/browse/WWW-124?focusedCommentId=13843) so they fit the available space, but aren't blurry.
1. Figure out a different way to do the "flow" for Patcher that works with large images, so that it's easy to skim down the page, spot headlines, etc.

Note also that these images show up on the [How it Works page](https://www.gruntwork.io/patcher/how-it-works), but at a different size (and as a result, blurry, as described in https://github.com/gruntwork-io/gruntwork-io.github.io/issues/619), so whatever solution we figure out for the Home Page should work for the How it Works page too.

**Comment by zackproser** [comment]
I spent a good amount of time experimenting with re-creating the patcher UI -> Open PR gif at different resolutions, including the exact resolution of [this image ](https://github.com/gruntwork-io/gruntwork-io.github.io/blob/d9c6cd3527bae1ea1af1ac16e7bdc7c7ac2037cb/assets/img/landing-page-enterprise/dependency-update.png), but ultimately the gifs, when presented in the tab viewer, are too small to be legible. 

Meanwhile, I feel that both gifs contain important text that _should_ be legible, becauseI believe they do a better job of demonstrating our intended UX than text and static images alone. Therefore, I opted to keep the widened gifs, and to re-order the headline and the image of a "featured" item in the how-it-works section of the homepage. If we're happy with this, I can also carry it across to the how-it-works page as well.

I am not claiming this is the best solution, but it's the one that appears ideal to me. Happy to switch it around as needed.
