### ISSUE TITLE
Patcher home page is wider than it should.

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/gruntwork-io.github.io#628]
![CPT2108251307-1202x761](https://user-images.githubusercontent.com/32835571/130771780-3fd06614-929a-4aef-8e77-2f61ab35063d.gif)

**Comment by ina-stoyanova** [comment]
This is happening on gruntwork.io & locally on master too, so I believe it hasn't been fixed in any of the more recent PR's

**Comment by ina-stoyanova** [comment]
Tagging @zackproser @brikis98 to get your thoughts on this! 

So after digging into this, me & @marinalimeira found out it's because of the "how it works" section. After pairing with @brikis98 we also realised it's because we were rendering an empty image tag with a set width. See fix commit here. 

Another last thing we noticed was that the gif expanding (the first one) has a reference to the renovate Github app. That's not easy to see, but once you know it, you know it :D

**Comment by zackproser** [comment]
> Tagging @zackproser @brikis98 to get your thoughts on this!
> 
> So after digging into this, me & @marinalimeira found out it's because of the "how it works" section. After pairing with @brikis98 we also realised it's because we were rendering an empty image tag with a set width. See fix PR here: https://github.com/gruntwork-io/gruntwork-io.github.io/compare/landing/patcher-fix-wider-page?expand=1.
> 
> Another last thing we noticed was that the gif expanding (the first one) has a reference to the renovate Github app. That's not easy to see, but once you know it, you know it :D

Thanks for spotting and fixing this @ina-stoyanova and @marinalimeira! I will re-create the gif now to remove the reference to `renovate`.
